version: '3'
services:
  front:
    image: shinyenggwak/clush-todo-front:0.0.1-SNAPSHOT
    networks:
      - my_network
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      REACT_APP_API_URL: spring-app:8080

  spring-app:
    image: shinyenggwak/clush-todo-back:0.0.3-RELEASE
    networks:
      - my_network
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      DBNAME : root
      DBPASS : rootsygwak
      DBURL : jdbc:mysql://mysql:3306/clush?useUnicode=true&characterEncoding=utf8

  mysql:
    image: "mysql"
    networks:
      - my_network
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/main/resources/db/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootsygwak
      MYSQL_DATABASE: clush
#      - MYSQL_USER = clush
#      - MYSQL_PASSWORD = sygwak

networks:
  my_network:
